# ===========================
# Configuracoes do Servidor
# ===========================
server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

# ===========================
# Configuracoes do Spring
# ==========================
spring:
  application:
    name: btg-leads-api
  datasource:
    # ===========================
    # Configuracoes do MySQL
    # ===========================
    url: jdbc:mysql://localhost:3306/btg_leads?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: SenhaSegura123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# =============================
# Swagger
# =============================
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.btg: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000  # 24h em ms

sonar:
  login: squ_1212f6dddb28db51faac843f335e72400c9785f9
  projectName: btg-leads-api